### ISSUE TITLE
long output display issue

### ISSUE THREAD

**Issue by luli11** [Calysto/matlab_kernel#54] opened 2016-06-13 13:41 UTC
This may very likely be a issue on matlab side, just wonder if there is a clever way to process it on matlab_kernel side.  whenever you have a large data set (e.g,a matrix that have several million row) as output and if you forget to use ";" to suppress output, it will try to copy all "millions" rows over and display it entirely. This simply freeze the whole front-end and render it useless.

**Comment by blink1073** [comment] 2016-06-13 13:52
Unfortunately, I think the only way to handle this is with an interrupt, since the python end is a "dumb" client.  Interrupts work when using the matlab engine, but not with `pymatbridge` currently.

**Comment by anntzer** [comment] 2016-09-01 06:35
Closed as duplicate of #5; particularly affected by the bug in wurlitzer as this is specifically about long outputs.

**Closed by anntzer** 2016-09-01 06:35 UTC
