### ISSUE TITLE
Jupyter - MatLab Kernel

### ISSUE THREAD

**Issue by gmur24** [Calysto/matlab_kernel#26] opened 2015-11-20 18:44 UTC
Hi - I can now see Matlab as one of the kernels. When I tried to create a new file, the kernel died and the Matlab software kept popping up until I close the kernel. Please help.

**Comment by blink1073** [comment] 2015-11-20 18:44
What operating system are you using?

**Comment by gmur24** [comment] 2015-11-20 18:46
Windows

**Comment by blink1073** [comment] 2015-11-20 18:47
What version?

**Comment by gmur24** [comment] 2015-11-20 18:48
sorry windows 10

**Comment by blink1073** [comment] 2015-11-20 18:52
hmm, I don't have access to Windows 10.  Does the same thing happen if you try to use `pymatbridge` by itself?  https://arokem.github.io/python-matlab-bridge/

**Comment by gmur24** [comment] 2015-11-20 18:53
you mean when I installed pymatbridge?

**Comment by blink1073** [comment] 2015-11-20 18:53
I mean using pymatbridge from a python console.

**Comment by gmur24** [comment] 2015-11-20 18:54
let me try that

**Comment by gmur24** [comment] 2015-11-20 18:56
nope

**Comment by blink1073** [comment] 2015-11-20 18:58
same issue?

**Comment by blink1073** [comment] 2015-11-20 18:59
See https://github.com/arokem/python-matlab-bridge/issues/226 and https://github.com/arokem/python-matlab-bridge/issues/220

**Comment by gmur24** [comment] 2015-11-20 19:02
nothing still

**Comment by blink1073** [comment] 2015-11-20 19:05
Sorry, I'm not sure what exactly could have changed between Windows versions, it may require a new build of the messenger MEX for pymatbridge.

**Comment by blink1073** [comment] 2016-05-20 17:40
Closing as the issue is with pymatbridge, not this library.

**Closed by blink1073** 2016-05-20 17:40 UTC
