### ISSUE TITLE
Kernel dies whenever it is interupted

### ISSUE THREAD

**Issue by univ3573** [Calysto/matlab_kernel#48] opened 2016-05-19 10:41 UTC
Hey guys,
Whenever I try to interupt the kernel in a jupyter notebook (either because I made a mistake or something is taking too long) it always dies). Anyone got a good guess as to why? I've had this problem with other kernels before but its getting super annoying!

Using jupyter installed in a virtual env on Fedora 21. No problems when running matlab in its native GUI.

Thanks, Alex

**Comment by dsblank** [comment] 2016-05-19 10:55
Can you get the versions for metakernel and matlab_kernel? Maybe something like:

```
pip list | grep "metakernel\|matlab"
```
What version of Python?

**Comment by univ3573** [comment] 2016-05-19 11:18
Thanks for your quick reply! Sorry I'm on a different machine right now I'll check as soon as I get back.
Alex

**Comment by univ3573** [comment] 2016-05-19 11:22
Python is 2.something -metakernel and matlab were installed as latest versions within the last couple of months

**Comment by univ3573** [comment] 2016-05-19 12:58
matlab-kernel (0.9.2)
metakernel (0.12.6)
Python (2.7.8)

**Comment by dsblank** [comment] 2016-05-19 13:45
Ok, thanks. Can you upgrade matlab-kernel to 0.9.4 and make sure that pymatbridge is 0.5.2?

**Comment by dsblank** [comment] 2016-05-19 13:45
Oh, and then test to see if the issue remains :)

**Comment by univ3573** [comment] 2016-05-19 14:45
Have done... Still there
`[I 15:44:53.922 NotebookApp] Kernel interrupted: f5a1ea92-cbbb-4ca5-98b0-a344d792f6dd
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/site-packages/pymatbridge/pymatbridge.py", line 239, in stop
    if self._response(cmd='exit') == "exit":
  File "/usr/lib/python2.7/site-packages/pymatbridge/pymatbridge.py", line 229, in _response
    self.socket.send_string(req)
  File "/home/data/.python_virtual_environments/ridge/lib/python2.7/site-packages/zmq/sugar/socket.py", line 383, in send_string
    return self.send(u.encode(encoding), flags=flags, copy=copy)
  File "zmq/backend/cython/socket.pyx", line 617, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6625)
  File "zmq/backend/cython/socket.pyx", line 664, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6363)
  File "zmq/backend/cython/socket.pyx", line 199, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2492)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
    raise ZMQError(errno)
ZMQError: Operation cannot be accomplished in current state
[I 15:44:56.841 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel f5a1ea92-cbbb-4ca5-98b0-a344d792f6dd restarted
/home/data/.python_virtual_environments/ridge/lib/python2.7/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
`

**Comment by dsblank** [comment] 2016-05-19 15:14
That is useful info. Thanks!

**Comment by blink1073** [comment] 2016-05-20 17:18
Hi @univ3573, I can confirm the behavior, I'll look at this today.

**Comment by blink1073** [comment] 2016-05-20 17:33
Ah, this is an issue with `pymatbridge`, see https://github.com/arokem/python-matlab-bridge/issues/164.

**Comment by blink1073** [comment] 2016-05-20 17:42
Closing as a duplicate of #5.  I'll try and address this in pymatbridge this weekend.

**Closed by blink1073** 2016-05-20 17:42 UTC

**Comment by blink1073** [comment] 2016-05-20 18:43
I don't see a good way around this.  You could try using the [octave_kernel](https://github.com/Calysto/octave_kernel), which does support interrupts, and set the `OCTAVE_EXECUTABLE` to your Matlab path.  I do not have a copy of Matlab to verify whether that will work (I use Octave to test this kernel).

**Comment by univ3573** [comment] 2016-05-20 18:58
I'll try it tomorrow morning and let you know. I have octave too. Thanks
