### ISSUE TITLE
Live feedback like ipython kernel

### ISSUE THREAD

**Issue by jayendra13** [Calysto/matlab_kernel#59] opened 2016-08-10 06:51 UTC
when some long computation is passed to kernel, it shows output only when it finishes it. Let say, if I execute

``` matlab
for i=1:10
     disp(i);
     pause(1);
end
```

This will show the all output at once. Unlike in ipython kernel when I executes the same code

``` python
import time
for i in xrange(10):
    print i
    time.sleep(1)
```

it shows the output when it gets evaluated.

Is it possible to add that feature here?

**Comment by blink1073** [comment] 2016-08-10 12:12
Hi @jayendra13, do you have the `matlab.engine` python package?  I do no personally have a Matlab license, so I can only test the kernel using Octave, and the snippet you gave does produce incremental output.

**Comment by jayendra13** [comment] 2016-08-10 15:11
In my case I am using `pymatbridge`. I will try `matlab.engine` if they provide it core matlab.

**Comment by blink1073** [comment] 2016-08-10 15:14
It could be that you've got an older version of `metakernel`, perhaps try `pip install -U metakernel`.

**Comment by scbarton** [comment] 2016-08-17 11:37
Using both matlab.engine and pymatbridge, with updated metakernel, get the same behavior.  Output is not returned until the cell is finished running.

**Comment by blink1073** [comment] 2016-08-17 14:34
Hi @scbarton, what OS and Python version are you using?

**Comment by scbarton** [comment] 2016-08-17 15:30
I use MacOS and Python 2.7.12. 

I've also tried the same test with the Octave kernel and it succeeds, giving output after every iteration.

**Comment by blink1073** [comment] 2016-08-17 15:54
Can you try launching the notebook server using the method below to see if it is a Matlab vs. Octave problem?

```
$ export OCTAVE_EXECUTABLE=`which octave` && jupyter notebook
```

**Comment by scbarton** [comment] 2016-08-17 18:29
That command leads to a crashing Matlab kernel with the error "NameError: global name 'Octave' is not defined"

**Comment by blink1073** [comment] 2016-08-18 13:09
Ah, right, can you please make this change to your source?

```diff
diff --git a/matlab_kernel/kernel.py b/matlab_kernel/kernel.py
index ce8a687..b45f04f 100644
--- a/matlab_kernel/kernel.py
+++ b/matlab_kernel/kernel.py
@@ -23,6 +23,7 @@ class MatlabEngine(object):

     def __init__(self):
         if 'OCTAVE_EXECUTABLE' in os.environ:
+            from pymatbridge import Octave
             self._engine = Octave(os.environ['OCTAVE_EXECUTABLE'])
             self._engine.start()
             self.name = 'octave'
```

**Comment by scbarton** [comment] 2016-08-19 01:20
I applied the above change to the source, and ran the notebook with

```$ export OCTAVE_EXECUTABLE=`which octave` && jupyter notebook```

The octave kernel behaves normally as described above

The matlab kernel errors out with the following:

```
error: javaMethod: Octave was not compiled with Java interface
error: called from
    javaclasspath at line 64 column 16
    json_startup at line 33 column 3
    matlabserver at line 6 column 1
error: evaluating argument list element number 2
error: called from
    json_startup at line 33 column 3
    matlabserver at line 6 column 1
error: evaluating argument list element number 1
error: called from
    json_startup at line 33 column 3
    matlabserver at line 6 column 1
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/matlab_kernel/__main__.py", line 3, in <module>
    MatlabKernel.run_as_main()
  File "/usr/local/lib/python2.7/site-packages/metakernel/_metakernel.py", line 103, in run_as_main
    MetaKernelApp.launch_instance(kernel_class=cls)
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 421, in initialize
    self.init_kernel()
  File "/usr/local/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 360, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matlab_kernel/kernel.py", line 111, in __init__
    self._matlab = MatlabEngine()
  File "/usr/local/lib/python2.7/site-packages/matlab_kernel/kernel.py", line 28, in __init__
    self._engine.start()
  File "/usr/local/lib/python2.7/site-packages/pymatbridge/pymatbridge.py", line 225, in start
    raise ValueError("%s failed to start" % self._program_name())
ValueError: Octave failed to start
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/pymatbridge/pymatbridge.py", line 239, in stop
    if self._response(cmd='exit') == "exit":
  File "/usr/local/lib/python2.7/site-packages/pymatbridge/pymatbridge.py", line 229, in _response
    self.socket.send_string(req)
  File "/usr/local/lib/python2.7/site-packages/zmq/sugar/socket.py", line 383, in send_string
    return self.send(u.encode(encoding), flags=flags, copy=copy)
  File "zmq/backend/cython/socket.pyx", line 617, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6625)
  File "zmq/backend/cython/socket.pyx", line 664, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6363)
  File "zmq/backend/cython/socket.pyx", line 199, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2492)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
    raise ZMQError(errno)
ZMQError: Operation cannot be accomplished in current state
```

For fun I re-compiled Octave with java enabled, which eliminated the java error, but still led to the ZMQ errors listed above.

**Comment by blink1073** [comment] 2016-08-19 21:21
Are you able to run:

$ export OCTAVE_EXECUTABLE=`which octave` && ipython

```python
from pymatbridge import Octave
octave = Octave(os.environ['OCTAVE_EXECUTABLE'])
```

**Comment by scbarton** [comment] 2016-08-20 15:43
I ran this:
```$ export OCTAVE_EXECUTABLE=which octave && ipython```

```
In [1]: import os

In [2]: from pymatbridge import Octave
   ...: octave = Octave(os.environ['OCTAVE_EXECUTABLE'])
   ...: octave
   ...: 
/usr/local/lib/python2.7/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)

Out[2]: <pymatbridge.pymatbridge.Octave at 0x10a8c1f50>
```

**Comment by blink1073** [comment] 2016-08-21 13:40
I just made a release that should clean up the engine selection.  Can you please try `pip install -U matlab_kernel` and then run `export OCTAVE_EXECUTABLE=`which octave` && jupyter notebook` again?

**Comment by scbarton** [comment] 2016-08-21 14:52
Here's my terminal session from the update and jupyter notebook session using the Octave kernel.  In short, the kernel would repeatedly crash when I tried to run Octave code.
[matlab_kernel octave.txt](https://github.com/Calysto/matlab_kernel/files/428903/matlab_kernel.octave.txt)

**Comment by blink1073** [comment] 2016-08-21 16:29
It looks like you started the `octave_kernel` itself, which is a different kernel altogether.  Please try the `Matlab` kernel in the dropdown.  Also, the command above got formatted improperly, should be:

 ```export OCTAVE_EXECUTABLE=`which octave` && jupyter notebook```

**Comment by scbarton** [comment] 2016-08-21 18:39
Sorry, here's an updated session using the correct export command and the MATLAB kernel:

[matlab_kernel matlab.txt](https://github.com/Calysto/matlab_kernel/files/429006/matlab_kernel.matlab.txt)

The error above is a missing `/usr/local/lib/libzmq.4.dylib`. I tried to correct that with `brew install zmq`. This only installed `libzmq.5.dylib`, so I symlinked .4 to .5.  Then I ran the kernel again, with these results.

[matlab_kernel matlab2.txt](https://github.com/Calysto/matlab_kernel/files/429014/matlab_kernel.matlab2.txt)

This failed because it was looking for a library in Octave 3.8.1 and I have 4.0.3.

Thanks for working on this, I'll be glad to continue helping!

**Comment by Foucl** [comment] 2016-08-22 12:25
I can confirm this behavior for matlab-native and matlab-pymatbridge on Windows (Python 2.7). I did some testing and put the following in ~/test_incr.m

```matlab
for i=1:10
     disp(i);
     pause(1);
end
```

A jupyter console running `matlab_kernel` (either using pymatbridge or the native engine) does not give incremental output.

From a jupyter console running a python2 kernel, things look a little different:

**pymatbridge**

```python
%load_ext pymatbridge
%matlab test_incr
```
no incremental output

**native matlab engine for python**
```python
import matlab.engine
eng = matlab.engine.start_matlab()
eng.test_incr(nargout=0)
``` 
-> incremental output works!
This also works with `eng.eval('test_incr', nargout=0)`

I know this issue is more about the pymatbridge implementation, but maybe @auneri has an idea how matlab_kernel's [`_run_native()`](https://github.com/Calysto/matlab_kernel/blob/master/matlab_kernel/kernel.py#L54-L80) could be modified so it shows incremental output. It probably has to do with the fact that output is stored in a StringIO() variable that is only returned after the execution of the whole block. If someone has an idea, I'd be happy to test it.

At least for me this would be quite useful as I only use Matlab for computationally rather intensive tasks (such as analysis of EEG data) where functions usually spit out some incremental progress report.

**Comment by dsblank** [comment] 2016-08-22 12:39
Yes, I think you are right: replacing StringIO with a class that wrote rather than appending to the string should work. (There is another problem with having a matlab_kernel as a magic and output going to the right place, but that is separate issue).

**Comment by Foucl** [comment] 2016-08-22 13:04
Could it be as simple as something like this: http://stackoverflow.com/a/14197079/3529249? The idea would be to create a context that both redirects to StringIO() (or somewhere else) and prints to the actual stdout. Or do you have a StringIO alternative in mind?

(I am sorry for a) creating noise in this issue and b) my very limited understanding of this/python/programming)

**Comment by dsblank** [comment] 2016-08-22 13:15
I think it would be even simpler than the SO solution: we just need a simple class replacement for StringIO. I think @blink1073 mentioned at one point that he had an idea.

**Comment by blink1073** [comment] 2016-08-24 13:26
I can look at this this weekend, rather swamped at the moment.

**Comment by blink1073** [comment] 2016-08-27 12:53
@anntzer, this could be solved by using `self.Print` and `self.Error` instead of stringio.

**Comment by anntzer** [comment] 2016-08-27 16:39
I think I still need a StringIO to pass in, but more specifically a subclass that also passes whatever gets written to `Print`/`Error`, or am I missing something?

**Comment by anntzer** [comment] 2016-08-28 06:40
In fact, after some testing, it seems that the matlab engine buffers everything (even with async=True) and dumps the text all at once at the end, so that's not going to work :(

**Comment by Foucl** [comment] 2016-08-28 09:12
Simple loops seem to work however (as [noted above](https://github.com/Calysto/matlab_kernel/issues/59#issuecomment-241397046) under 'native matlab engine for python'). I put the loop in script though, not a function, so maybe that's why it worked. So you are sure the issue lies on the matlab side? That's a pity. Thank you very much for trying anyway!

**Comment by anntzer** [comment] 2016-08-28 18:39
Good catch...
After some more investigation it appears that the engine writes to the output asynchronously when it directly goes to stdout, but dumps everything in one go when passed an explicit `out` variable (which we need to do... but see below), thus explaining your observation.
What's worse is that MATLAB (not so unexpectedly) does not obey Python's `sys.stdout`, so the only way I can see how to make this work would be to redirect the C-level stdout of the kernel process (so that MATLAB thinks it is writing to a normal stdout) to pipe into another fd, and redirect reads from this fd to `self.Print`.  Sounds like a lot of fun...

**Comment by jayendra13** [comment] 2016-08-31 03:21
ahh!! I was on vacation and was not able to check the things. Can any one point me the code where modifications are needed?

**Comment by anntzer** [comment] 2016-08-31 04:16
It basically still doesn't work due to the limitations mentioned above.  I am reasonably confident that the fix I suggested may make it work, but it's far from trivial to implement.  If anyone wants to give it a try...

**Comment by anntzer** [comment] 2016-08-31 05:22
Actually it turns out that the jupyter developers already did [all the hard work](https://github.com/minrk/wurlitzer).  Try master with `pip install git+https://github.com/Calysto/matlab_kernel`.

**Comment by Foucl** [comment] 2016-08-31 12:13
Thank you @anntzer , looks really good! However, I can't test it, as I am on windows and wurlitzer seems to depend on fcntl (https://github.com/minrk/wurlitzer/blob/master/wurlitzer.py#L19), which is not available for that platform - so right now matlab_kernel is 'broken' for me. Should I raise an issue there?

**Comment by blink1073** [comment] 2016-08-31 12:34
This may be of help: http://stackoverflow.com/a/34504971

**Comment by scbarton** [comment] 2016-08-31 13:53
I can confirm that the version of `matlab_kernel` with `wurlitzer` does provide live feedback.  Thank you!

**Comment by anntzer** [comment] 2016-08-31 16:16
@Foucl I'm sure they will appreciate a PR with a solution similar to the one that @blink1073 pointed to 😃

**Comment by Foucl** [comment] 2016-08-31 17:56
okay, I will experiment a bit, thank you all very much for taking a look and practically solving this. If I'll come up with a solution and even manage to submit a PR, I'll post here.

**Comment by anntzer** [comment] 2016-09-01 06:38
By the way there's another issue in wurlitzer (https://github.com/minrk/wurlitzer/issues/1) which causes freezing on long outputs.  I think we need to get it resolved as well as figuring out Windows support (well, those actually using Windows need to do at least the second part :p) before I can make a release with this fix.

**Comment by Foucl** [comment] 2016-09-19 05:44
I took a look at porting wurlitzer to windows. Using `SetNamedPipeHandleState` as described in the [SO answer](http://stackoverflow.com/questions/34504970/non-blocking-read-on-os-pipe-on-windows/34504971#34504971) linked by blink1073 seems to work. However, I realized that this is not the only thing preventing matlab_kernel to work with Windows right now: You switched to only supporting Python 3.5 and - at least for R2016a - the windows version of the matlab engine for python only supports Python up to 3.4.

**Comment by anntzer** [comment] 2016-09-19 07:16
If I did drop support for Py3.4 that was an accident -- I don't really want to maintain a Py2/Py3 codebase but I'm not that much of an extremist :-)
Please let me know what fix I need to revert.

**Comment by Foucl** [comment] 2016-09-19 07:58
nothing in the code itself I think, only in setup.py ([Line 8](https://github.com/Calysto/matlab_kernel/blob/master/setup.py#L8)) and the wording of the ImportError. I changed it to `if sys.version_info < (3, 4)` and it seems to install fine (after removing the Wurlitzer-related parts from kernel.py). you could probably just do `sys.version_info.major < 3`

**Comment by anntzer** [comment] 2016-09-19 08:09
I have decreased the version requirement to 3.4 (which is still needed due to the use of pathlib).
Be careful, I have edited the history to replace the offending commit.  I have also added a new commit as I found that the kernel could wait for the result in the main thread instead of spawning a new thread, so it'd be nice if you could confirm that as well.

**Comment by Foucl** [comment] 2016-09-19 08:31
Ok, while trying to do that I noticed that your code does depend on 3.5: in do_complete, you use pathlib's `write_text`, which is only available in 3.5 ([L152](https://github.com/Calysto/matlab_kernel/blob/master/matlab_kernel/kernel.py#L152)). After commenting this (and the `with Wurlitzer`) out, I can run Matlab code.

I am, however, sorry that I do not understand your change completely:

> I found that the kernel could wait for the result in the main thread instead of spawning a new thread

How could I test/confirm that? Right now, everything seems to work (when I launch a QTConsole, I see the output of my commands in the cmd window (not in the console itself of course, as Wurlitzer is not implemented yet)).

**Comment by Foucl** [comment] 2016-09-19 09:28
Hm, wurlitzer also uses `select` in `forwarder`, which doesn't work on pipes in Windows. My enthusiasm is starting to fade... Maybe sockets will be necessary. I have no idea where to start - do you have any pointers, maybe similar projects? Would it be okay to ask in the Wurlitzer repo for some getting-started help?

**Comment by Foucl** [comment] 2016-09-19 18:16
Just tried in a docker image (jupyter/docker-stacks/scipy-notebook) and both incremental output and kernel interrupts work. the latter also work in Windows.

Concerning Windows Support: I'll try to do some research and ask at the wurlitzer repo. It's a pity, as the docker solution will probably become really slow for computationally intensive tasks. I'll just have to revert to a pre-Wurlitzer version, not too bad.

**Comment by ksarma** [comment] 2016-09-28 00:32
Hmm, I just tried this out on a linux box (not the docker image referenced above) and it didn't work for me. Not sure if I'm doing something wrong. I used pip to install master (using the github repo) on this and then reinstalled the kernel. Running the code at the top (which pauses and prints 1-10) still causes the same behavior on my system (i.e. output is only produced after completion of the whole loop)

**Comment by anntzer** [comment] 2016-09-28 06:22
Can you also install metakernel from master and make sure you have the most recent release of jupyter?  What is the version of MATLAB?  Please check the output of `jupyter kernelspec list`.  It should contain a line
```
  matlab     /some/path/matlab
```
What is the content of `/path/to/matlab/kernel.json` (where `path/to/matlab` is as above)?

**Comment by anntzer** [comment] 2016-09-28 17:31
@jayendra13 @scbarton @Foucl @ksarma 
I have implemented socket-based redirection in my `socket-redirection` branch (https://github.com/anntzer/matlab_kernel/tree/socket-redirection).  It should now work on all OSes (only tested on Linux though, but looking for your feedback re: MacOS and Windows).
The implementation requires `socketpair` which is only available since Py3.5 on Windows, so I increased the oldest supported version back to 3.5 (and thus you will also need MATLAB2016b).

**Comment by ksarma** [comment] 2016-09-28 19:43
@anntzer Thanks for your help! I installed metakernel and jupyter from master, then reinstalled matlab_kernel from master and now running the test code from the top of this issue does produce the expected behavior. Also, interrupting seems to work as well! :)

Unfortunately I don't currently have 2016B installed on my machine, so I can't test your branch out yet. Will talk to our licensing people and see if we can upgrade; if so will get back to you (though I only use linux as well, so maybe not very helpful)

**Comment by anntzer** [comment] 2016-09-28 20:29
You can test my branch with 3.4 on Linux as well, you just need to get rid of the version check in setup.py.

Depending on how things go, I may release a 3.5 wheel on PyPI once everything is fixed but drop the explicit version check in setup.py, so that 3.4 support stays unofficially available (but you'll need to install from the repo).

**Comment by Foucl** [comment] 2016-09-29 07:15
thank, @anntzer! I'll test on my docker container later. I'll also find out when my university's Matlab license servers will be updated to support 2016b. Maybe I'll try some workarounds (like http://stackoverflow.com/questions/24933411/how-to-emulate-socket-socketpair-on-windows) on my fork.

**Comment by anntzer** [comment] 2016-10-13 14:27
Add `Path.write_text = lambda self, data: self.open("w").write(data)` before that line.

**Comment by anntzer** [comment] 2016-10-14 16:40
@Foucl I just gave it a try myself and it's still not going to work on Windows :-( You can't dup2 a socket there, apparently.  Basically due to http://stackoverflow.com/questions/34557198/when-i-use-os-dup2-on-windows-i-get-an-error-oserror-errno-9-bad-file-des.

In fact the `dup2` entry at https://tangentsoft.net/wskfaq/articles/bsd-compatibility.html suggests that none of these are going to work and that the only real solution is to start the engine in a separate process and connect to its stdin and stdout.  Any asyncio experts here? :-)

**Comment by anntzer** [comment] 2016-10-16 06:45
To be honest I feel writing the code for starting a separate process basically amounts to redoing the work that was done in pymatbridge, so it's not worth it (you may as well fix pymatbridge and get to support older versions of everything, then).

I also had a quick look at the other engines MATLAB provides.  The C API (which you could call through ctypes -- everything is in `libeng.so`) is basically useless as it outputs to a `char*` buffer instead of stdout (http://www.mathworks.com/help/matlab/apiref/engevalstring.html).  The Java API, however, provides the ability to pass a *Writer* to `eval` (http://www.mathworks.com/help/matlab/apiref/com.mathworks.engine.matlabengine-class.html#bvarmmm-1) (basically the equivalent of a writable file-like in Python); additionally, a quick test showed me that the output is written in real time to the Writer (rather than everything at once as the Python engine does).

So a strategy to support Windows would be to call the MATLAB Java engine (e.g. via https://pypi.python.org/pypi/javabridge), open a pipe or socket, let the engine write on one side and the kernel read on the other side.  No need for `dup2` anymore!

To be honest I'm not going to bother.  One of the reasons is that async support for any of the engines is weak anyways: for example, whether using the Python or the Java engine, something like
```
start(timer('timerfcn', 'disp(42)'))
```
does not output anything (even without messing up with the redirection) -- probably because MATLAB has closed stdout for this task by the time `disp(42)` is reached.

**Comment by Foucl** [comment] 2016-10-16 10:33
There doesn't seem to be a lot of demand for Windows support anyway (besides me ;-)). Thanks for investigating! Btw, [matlab_wrapper](https://github.com/mrkrd/matlab_wrapper) is/was a package that uses Matlab's C engine (without live feedback of course).

**Comment by anntzer** [comment] 2016-10-16 19:23
The FAQ of matlab_wrapper points you to a ton of existing wrappers.  Unfortunately it appears that none of them really fixes everything.

**Comment by anntzer** [comment] 2016-10-18 08:53
Oh, and for additional lolz, Java does not seem to support opening arbitrary file descriptors such as those that socketpair returns by default (unless you do weird unsupported tricks with reflection), so even more work!

**Comment by blink1073** [comment] 2017-02-15 10:48
Live output is supported on POSIX-like systems.  Closing as fixed.

**Closed by blink1073** 2017-02-15 10:48 UTC
